<template>
    <div class="flex w-full items-center flex-wrap">
        <div v-for="emoji in emojis" :key="emoji">
            <ul>
                <li
                    class="p-0.5 cursor-pointer"
                    :class="{
                        'text-xl': size === 'xl',
                        'text-lg': size === 'lg',
                        'text-base': size === 'base',
                        'text-sm': size === 'sm',
                    }"
                    @click="$emit('addEmoji', emoji)">
                    {{ emoji }}
                </li>
            </ul>
        </div>
    </div>
</template>

<script>
export default {
    props: {
        size: {
            type: String,
            default: 'xl',
        },
    },
    data: function () {
        return {
            emojis: [
                '😀',
                '😃',
                '😄',
                '😁',
                '😆',
                '😅',
                '🤣',
                '😂',
                '🙂',
                '🙃',
                '😉',
                '😊',
                '😇',
                '🥰',
                '😍',
                '🤩',
                '😘',
                '😗',
                '😚',
                '😙',
                '🥲',
                '😋',
                '😛',
                '😜',
                '🤪',
                '😝',
                '🤑',
                '🤗',
                '🤭',
                '🤫',
                '🤔',
                '🤐',
                '🤨',
                '😐',
                '😑',
                '😶',
                '😏',
                '😒',
                '🙄',
                '😬',
                '😮‍💨',
                '🤥',
                '😌',
                '😔',
                '😪',
                '🤤',
                '😴',
                '😷',
                '🤒',
                '🤕',
                '🤢',
                '🤮',
                '🤧',
                '🥵',
                '🥶',
                '🥴',
                '😵',
                '🤯',
                '🤠',
                '🥳',
                '🥸',
                '😎',
                '🤓',
                '🧐',
                '😕',
                '😟',
                '🙁',
                '☹️',
                '☹',
                '😮',
                '😯',
                '😲',
                '😳',
                '🥺',
                '😦',
                '😧',
                '😨',
                '😰',
                '😥',
                '😢',
                '😭',
                '😱',
                '😖',
                '😣',
                '😞',
                '😓',
                '😩',
                '😫',
                '🥱',
                '😤',
                '😡',
                '😠',
                '🤬',
                '😈',
                '👿',
                '💀',
                '☠️',
                '☠',
                '💩',
            ],
        }
    },
}
</script>
